'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';

type Client = { id:number; name:string; hourly_rate_cents:number|null };
type Project = { id:number; client_id:number; name:string; color:string; hourly_rate_cents:number|null };
type Entry = { id:number; project_id:number; started_at:string; ended_at:string; description:string; billable:number; invoiced:number; hourly_rate_cents:number; rate_source:string; project_name:string; project_color:string; client_name:string };
type Data = { clients:Client[]; projects:Project[]; entries:Entry[] };
type View = 'registro'|'clienti'|'progetti'|'report';
const today = () => new Date().toLocaleDateString('sv-SE');
const money = (c:number) => new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(c/100);
const minutes = (e:Entry) => Math.max(0,(new Date(e.ended_at).getTime()-new Date(e.started_at).getTime())/60000);
const duration = (m:number) => `${Math.floor(m/60)}h ${Math.round(m%60).toString().padStart(2,'0')}m`;
const amount = (e:Entry) => Math.round(minutes(e)*e.hourly_rate_cents/60);
const localInput = (iso:string) => { const d=new Date(iso); const z=d.getTimezoneOffset(); return new Date(d.getTime()-z*60000).toISOString().slice(0,16); };

export default function TempoApp(){
  const [data,setData]=useState<Data>({clients:[],projects:[],entries:[]}); const [view,setView]=useState<View>('registro'); const [date,setDate]=useState(today()); const [modal,setModal]=useState<null|'entry'|'client'|'project'>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  useEffect(()=>{if('serviceWorker' in navigator)void navigator.serviceWorker.register('/sw.js');void fetch('/api/data').then(r=>{if(!r.ok)throw new Error();return r.json()}).then(value=>{setData(value);setError('')}).catch(()=>setError('Impossibile caricare i dati.')).finally(()=>setLoading(false))},[]);
  const mutate=async(method:string,body?:object,url='/api/data')=>{setError('');const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});if(!r.ok){setError('Operazione non riuscita.');return false}setData(await r.json());return true};
  const dayEntries=data.entries.filter(e=>localInput(e.started_at).slice(0,10)===date); const dayMinutes=dayEntries.reduce((s,e)=>s+minutes(e),0); const dayAmount=dayEntries.reduce((s,e)=>s+amount(e),0); const uninvoiced=data.entries.filter(e=>e.billable&&!e.invoiced).reduce((s,e)=>s+amount(e),0);
  const changeDay=(n:number)=>{const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+n);setDate(d.toLocaleDateString('sv-SE'))};
  return <main className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">T</span><span>Tempo</span></div><nav>{([['registro','Registro'],['clienti','Clienti'],['progetti','Progetti'],['report','Report']] as [View,string][]).map(([key,label])=><button className={view===key?'active':''} key={key} onClick={()=>setView(key)}>{label}</button>)}</nav><div className="sidebar-foot">{new Date().toLocaleDateString('it-IT',{day:'numeric',month:'long',year:'numeric'})}<br/><strong>{duration(dayMinutes)}</strong> registrate</div></aside>
    <section className="workspace">{error&&<div className="error">{error}</div>}{loading?<div className="loading">Caricamento…</div>:<>
      {view==='registro'&&<Registro entries={dayEntries} date={date} dayMinutes={dayMinutes} dayAmount={dayAmount} uninvoiced={uninvoiced} changeDay={changeDay} setDate={setDate} newEntry={()=>setModal(data.projects.length?'entry':'project')} mutate={mutate}/>} 
      {view==='clienti'&&<Collection title="Clienti" subtitle="Tariffe predefinite e storico dei clienti." button="Nuovo cliente" onAdd={()=>setModal('client')} empty="Non hai ancora creato clienti.">{data.clients.map(c=><article className="collection-row" key={c.id}><div><strong>{c.name}</strong><span>{data.projects.filter(p=>p.client_id===c.id).length} progetti</span></div><b>{c.hourly_rate_cents?`${money(c.hourly_rate_cents)}/ora`:'Nessuna tariffa'}</b></article>)}</Collection>}
      {view==='progetti'&&<Collection title="Progetti" subtitle="Ogni progetto appartiene a un cliente." button="Nuovo progetto" onAdd={()=>setModal(data.clients.length?'project':'client')} empty="Crea prima un cliente, poi il suo primo progetto.">{data.projects.map(p=><article className="collection-row" key={p.id}><span className="project-chip" style={{background:p.color}}/><div><strong>{p.name}</strong><span>{data.clients.find(c=>c.id===p.client_id)?.name}</span></div><b>{p.hourly_rate_cents?`${money(p.hourly_rate_cents)}/ora`:'Tariffa cliente'}</b></article>)}</Collection>}
      {view==='report'&&<Reports entries={data.entries}/>}</>}
    </section>{modal&&<Modal type={modal} data={data} close={()=>setModal(null)} save={async b=>{if(await mutate('POST',b))setModal(null)}}/>}
  </main>
}

function Registro({entries,date,dayMinutes,dayAmount,uninvoiced,changeDay,setDate,newEntry,mutate}:{entries:Entry[];date:string;dayMinutes:number;dayAmount:number;uninvoiced:number;changeDay:(n:number)=>void;setDate:(d:string)=>void;newEntry:()=>void;mutate:(m:string,b?:object,u?:string)=>Promise<boolean>}){
 return <><header className="topbar"><div><p className="eyebrow">{new Date(`${date}T12:00`).toLocaleDateString('it-IT',{weekday:'long',day:'numeric',month:'long'})}</p><h1>Il tuo tempo</h1></div><button className="primary" onClick={newEntry}>＋ Nuovo slot</button></header><div className="summary-grid"><div className="summary-card"><span>Giornata</span><strong>{duration(dayMinutes)}</strong><small>{money(dayAmount)}</small></div><div className="summary-card"><span>Slot registrati</span><strong>{entries.length}</strong><small>nel giorno selezionato</small></div><div className="summary-card accent"><span>Da fatturare</span><strong>{money(uninvoiced)}</strong><small>su tutte le attività</small></div></div><div className="panel"><div className="panel-head"><div><h2>Registro giornaliero</h2><p>La tariffa resta quella salvata sulla singola attività.</p></div><div className="date-nav"><button onClick={()=>changeDay(-1)}>‹</button><input aria-label="Data" type="date" value={date} onChange={e=>setDate(e.target.value)}/><button onClick={()=>setDate(today())}>Oggi</button><button onClick={()=>changeDay(1)}>›</button></div></div>{entries.length?<div className="entry-list">{entries.map(e=><article className="entry" key={e.id}><time>{new Date(e.started_at).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}–{new Date(e.ended_at).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}</time><span className="dot" style={{background:e.project_color}}/><div className="entry-main"><strong>{e.project_name}</strong><span>{e.client_name}{e.description?` · ${e.description}`:''}</span></div><div className="entry-total"><strong>{duration(minutes(e))}</strong><span>{money(e.hourly_rate_cents)}/ora · {money(amount(e))}</span></div><label className="invoice-check" title="Fatturata"><input type="checkbox" checked={!!e.invoiced} onChange={x=>mutate('PATCH',{type:'entry',id:e.id,invoiced:x.target.checked})}/><span>✓</span></label><button aria-label="Elimina attività" className="trash" onClick={()=>mutate('DELETE',undefined,`/api/data?id=${e.id}`)}>×</button></article>)}</div>:<div className="empty"><strong>Nessuno slot in questa giornata</strong><span>Aggiungi il tempo dedicato a un progetto.</span></div>}<button className="add-row" onClick={newEntry}>＋ Aggiungi uno slot di tempo</button></div></>
}
function Collection({title,subtitle,button,onAdd,empty,children}:{title:string;subtitle:string;button:string;onAdd:()=>void;empty:string;children:React.ReactNode}){return <><header className="topbar"><div><p className="eyebrow">Anagrafica</p><h1>{title}</h1><p className="page-subtitle">{subtitle}</p></div><button className="primary" onClick={onAdd}>＋ {button}</button></header><div className="panel collection">{children||<div className="empty"><strong>{empty}</strong></div>}</div></>}

function Reports({entries}:{entries:Entry[]}){const [from,setFrom]=useState(()=>{const d=new Date();d.setDate(1);return d.toLocaleDateString('sv-SE')});const [to,setTo]=useState(today());const filtered=useMemo(()=>entries.filter(e=>localInput(e.started_at).slice(0,10)>=from&&localInput(e.started_at).slice(0,10)<=to),[entries,from,to]);const totalM=filtered.reduce((s,e)=>s+minutes(e),0),totalC=filtered.reduce((s,e)=>s+amount(e),0);
 const csv=()=>{const rows=[['Data','Inizio','Fine','Durata','Cliente','Progetto','Descrizione','Fatturabile','Fatturato','Tariffa','Importo'],...filtered.map(e=>[e.started_at.slice(0,10),localInput(e.started_at).slice(11),localInput(e.ended_at).slice(11),duration(minutes(e)),e.client_name,e.project_name,e.description||'',e.billable?'Sì':'No',e.invoiced?'Sì':'No',(e.hourly_rate_cents/100).toFixed(2),(amount(e)/100).toFixed(2)])];download('\ufeff'+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n'),`tempo_${from}_${to}.csv`,'text/csv;charset=utf-8')};
 const pdf=async()=>{const {jsPDF}=await import('jspdf');const doc=new jsPDF();doc.setFontSize(20);doc.text('Report attività',16,20);doc.setFontSize(10);doc.text(`${new Date(from+'T12:00').toLocaleDateString('it-IT')} – ${new Date(to+'T12:00').toLocaleDateString('it-IT')}`,16,28);let y=40;filtered.forEach(e=>{if(y>275){doc.addPage();y=20}doc.setFontSize(10);doc.text(`${e.started_at.slice(0,10)}  ${e.client_name} / ${e.project_name}`,16,y);doc.text(duration(minutes(e)),150,y);doc.text(money(amount(e)),177,y,{align:'right'});doc.setFontSize(8);doc.setTextColor(110);doc.text(e.description||'—',16,y+5);doc.setTextColor(0);y+=13});doc.line(16,y,194,y);doc.setFontSize(12);doc.text(`Totale: ${duration(totalM)}  ·  ${money(totalC)}`,16,y+9);doc.save(`tempo_${from}_${to}.pdf`)};
 return <><header className="topbar"><div><p className="eyebrow">Esportazioni</p><h1>Report</h1><p className="page-subtitle">Riepiloga ed esporta le attività registrate.</p></div><div className="export-actions"><button onClick={csv}>CSV</button><button className="primary" onClick={pdf}>PDF</button></div></header><div className="report-filters"><label>Dal<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Al<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><div className="summary-grid report-summary"><div className="summary-card"><span>Tempo</span><strong>{duration(totalM)}</strong></div><div className="summary-card"><span>Importo</span><strong>{money(totalC)}</strong></div><div className="summary-card accent"><span>Attività</span><strong>{filtered.length}</strong></div></div><div className="panel report-table">{filtered.map(e=><div className="report-row" key={e.id}><span>{new Date(e.started_at).toLocaleDateString('it-IT')}</span><div><strong>{e.project_name}</strong><small>{e.client_name}</small></div><b>{duration(minutes(e))}</b><b>{money(amount(e))}</b></div>)}{!filtered.length&&<div className="empty">Nessuna attività nell’intervallo.</div>}</div></>}
function download(content:string,name:string,type:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}

function Modal({type,data,close,save}:{type:'entry'|'client'|'project';data:Data;close:()=>void;save:(b:object)=>Promise<void>}){const [busy,setBusy]=useState(false);const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const o=Object.fromEntries(f.entries());if(type==='entry'){o.startedAt=new Date(String(o.startedAt)).toISOString();o.endedAt=new Date(String(o.endedAt)).toISOString();o.billable=f.has('billable')?'true':''}await save({type,...o,billable:type==='entry'?f.has('billable'):undefined});setBusy(false)};const start=new Date();start.setMinutes(0,0,0);const end=new Date(start.getTime()+3600000);
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><form className="modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">Nuovo elemento</p><h2>{type==='entry'?'Slot di tempo':type==='client'?'Cliente':'Progetto'}</h2></div><button type="button" onClick={close}>×</button></div>{type==='client'&&<><label>Nome<input name="name" required autoFocus placeholder="es. Acme S.r.l."/></label><label>Tariffa predefinita €/ora<input name="hourlyRate" type="number" min="0" step="0.01" placeholder="65,00"/></label></>}{type==='project'&&<><label>Cliente<select name="clientId" required>{data.clients.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Nome progetto<input name="name" required autoFocus placeholder="es. Sito corporate"/></label><div className="form-grid"><label>Colore<input name="color" type="color" defaultValue="#5b5bd6"/></label><label>Tariffa specifica €/ora<input name="hourlyRate" type="number" min="0" step="0.01" placeholder="Eredita dal cliente"/></label></div></>}{type==='entry'&&<><label>Progetto<select name="projectId" required>{data.projects.map(p=><option value={p.id} key={p.id}>{data.clients.find(c=>c.id===p.client_id)?.name} — {p.name}</option>)}</select></label><div className="form-grid"><label>Inizio<input name="startedAt" type="datetime-local" required defaultValue={localInput(start.toISOString())}/></label><label>Fine<input name="endedAt" type="datetime-local" required defaultValue={localInput(end.toISOString())}/></label></div><label>Descrizione<input name="description" placeholder="Cosa hai fatto?"/></label><label>Tariffa manuale €/ora<input name="hourlyRate" type="number" min="0" step="0.01" placeholder="Usa quella del progetto o cliente"/></label><label className="check"><input type="checkbox" name="billable" defaultChecked/> Attività fatturabile</label></>}<div className="modal-actions"><button type="button" onClick={close}>Annulla</button><button className="primary" disabled={busy}>{busy?'Salvataggio…':'Salva'}</button></div></form></div>}
